### ISSUE TITLE
Add conditional loading of facades too

### ISSUE THREAD

**Issue by sebastiaanluca** [sebastiaanluca/laravel-conditional-providers#1]
Not sure if necessary/wanted, but currently there's no way to define a facade/alias per environment.

**Comment by it-can** [comment]
Yes please

**Comment by it-can** [comment]
I added a PR #2

**Comment by sebastiaanluca** [comment]
Hey @it-can, thanks for the PR! Much appreciated. I'll check it out and merge it asap, adding some tests along the way.

**Comment by sebastiaanluca** [comment]
Done! Will create a new release in just a moment.
