### ISSUE TITLE
[Question] how is it going to work with the new 5.5 auto discovery

### ISSUE THREAD

**Issue by ctf0** [sebastiaanluca/laravel-conditional-providers#3]
with the new release v5.5 , service providers are no longer being added to the config, so how the package tackle this if laravel already register all discovered SP as global providers ?

**Comment by ctf0** [comment]
from what i understand is laravel run the auto-disc after the dump-autoload, which means after you have registered your sp under `config/app`, 
so the question is 
**does laravel override whatever you have already registered and still use the auto-disc instead ?**

**Comment by ctf0** [comment]
**update**

adding packages to `dont-discover` works

**Comment by sebastiaanluca** [comment]
Great idea about using the package name, will look into that. Would only be possible if Laravel somehow lets us dynamically add packages to Composer's `dont-discover` though. Then I can unregister the package if it's in an conditional environment array and re-register if in that specific environment.

With Laravel 5.5, I find that you have 2 options:

1. Fully rely on Laravel 5.5's auto-discovery and composer's `require` and `require-require` keys. Then run `composer install --no-dev` on your production server so development packages won't get installed nor auto-discovered. Works great if you only want to conditionally load packages in a local and/or production environment.
2. Add the environment-specific package to `composer.json`'s `dont-discover` first and then add it to a specific environment provider or facade key(s) like you would usually do. Best solution if you have more environments than just local and production (`require` vs `require-dev`) and need to load it conditionally.

I'll update the readme asap.

**Comment by ctf0** [comment]
for the prev idea, actually we can have a work around.

- laravel save the auto-disc in `bootstrap/cache/packages.php`, 
- we make a command that gets add under `post-autoload-dump` script
- cleanup `packages.php` according to config

however we need a better GLOBAL solution, to handle both auto-disc & normal packages sp registration.

**Comment by sebastiaanluca** [comment]
Sorry about the late reply.

For now, I'd rather stick to a near-native solution. I don't want to meddle in generated files. Most people will only have a local and production environment anyway, so they can use composer's `require` and `require-dev` keys and let Laravel do its magic.

For those of us that have additional environments like staging _and_ need to conditionally load package, we just need to add those to composer's `dont-discover` key and use this package to load them in the desired environment. I suppose that's still pretty easy to do for the limited situations it's needed?

For anyone using Laravel 5.4 and before, nothing changes anyway.

**Comment by ctf0** [comment]
i think that same, cuz any solution we come up with will require the usre defining what package to be reg under which env, so sticking to `dont-discover` will suffice

**Comment by sebastiaanluca** [comment]
I'll update the readme to make this more clear when I have some time.
